### ISSUE TITLE
No module named 'textclf.utils'

### ISSUE THREAD

**Issue by renmada** [luopeixiang/textclf#2]
pip装的
(base) vocust001@ubuntu:~/anaconda3/lib/python3.7/site-packages$ textclf 
Traceback (most recent call last):
  File "/home/vocust001/anaconda3/bin/textclf", line 11, in <module>
    load_entry_point('textclf==0.1.0', 'console_scripts', 'textclf')()
  File "/home/vocust001/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/vocust001/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/home/vocust001/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/vocust001/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/vocust001/anaconda3/lib/python3.7/site-packages/textclf-0.1.0-py3.7.egg/textclf/main.py", line 9, in <module>
  File "/home/vocust001/anaconda3/lib/python3.7/site-packages/textclf-0.1.0-py3.7.egg/textclf/data/__init__.py", line 1, in <module>
    # -*- coding: utf-8 -*-
  File "/home/vocust001/anaconda3/lib/python3.7/site-packages/textclf-0.1.0-py3.7.egg/textclf/data/raw.py", line 5, in <module>
  File "/home/vocust001/anaconda3/lib/python3.7/site-packages/textclf-0.1.0-py3.7.egg/textclf/data/dictionary.py
ModuleNotFoundError: No module named 'textclf.utils'

**Comment by qijunhui** [comment]
解决了吗？我也是遇到 No module named 'textclf.utils'

**Comment by luopeixiang** [comment]
pip安装可能有点问题，可以尝试clone整个仓库，然后在项目目录下面运行 `pip install -e .`
